const base = {
  report: '/reports',
  programs: 'programs'
}
export const endpoints = {
  signup: '/signup',
  accountBalance: '/account-balance',
  aggregationCampaigns: 'aggregation-campaigns',
  aggregationReports: `${base.report}/aggregation-reports`,
  aggregationStats: `${base.report}/aggregation-stats`,
  aggregations: `/aggregations`,
  inventoriesStat: `${base.report}/inventories-stats`, //
  paymentStat: `${base.report}/payment-stats`, //
  redemptionsStat: `${base.report}/redemptions-stats`,
  redemptionsReports: `${base.report}/redemptions-reports`,
  inventoriesRedemptionReports: `${base.report}/inventories-redemption-reports`,
  suppliersStats: `${base.report}/suppliers-stats`,
  distributorStats: `${base.report}/distributors-stats`,
  retailersStats: `${base.report}/retailers-stats`,
  redemptionTrends: `${base.report}/redemptions-trends`,
  primaryCommodityStats: `${base.report}/primary-commodity-stats`,
  programRetailers: `${base.report}/program-retailers`,
  supplierAllocationsReports: `${base.report}/suppliers-allocations-reports`,
  redemptionCollectionStats: `${base.report}/redemptions-collections-stats`,
  redemptionsCollectionsReports: `${base.report}/redemptions-collections-reports`,
  monitoringSchedulesReports: `${base.report}/monitoring-schedules-reports`,
  commodityEstimatedYieldStats: `${base.report}/commodity-estimated-yield-stats`,
  farmerStats: `${base.report}/farmer-data-stats`,
  farmerFarmsStats: `${base.report}/farmer-farms-stats`,
  auth: 'auth',
  processSettledAggregation: `/aggregations/process-settle-aggregation`,
  agents: '/agents',
  programs: 'programs',
  commodities: 'commodities',
  waybills: '/inventories',
  retail_outlets: '/retail-outlets',
  aggregationOutlets: '/aggregation-outlets',
  distributors: `/distributors`,
  inputs: '/inputs',
  supplierAllocations: '/supplier-allocations',
  collections: 'collections',
  farmers: 'farmers',
  commodityScheduleTemplates: '/commodity-schedule-templates',
  monitoringActivities: '/monitoring-activities/activities-config',
  organisations: '/organisations',
  collect: '/collect',
  payments: '/payments',
  users: '/users',
  locations: '/locations',
  vcas: '/vcas',
  questionnaire: '/questionnaire',
  schemas: '/schemas',
  messages: '/messages',
  chats: '/messages/chats',
  marketProductList: 'market-products',
  marketOrders: 'market-orders',
  agentFarmer: 'farmer',
  agentFarmers: 'agent-farmer'
}
